"""
PDF Report Generator Agent - Creates professional SOP PDF reports
"""
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle, PageBreak
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from PIL import Image as PILImage
import os
from typing import Dict, Any, List

class PDFGeneratorAgent:
    """Generates professional SOP PDF reports"""
    
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()
    
    def _setup_custom_styles(self):
        """Setup custom paragraph styles"""
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#1a237e'),
            spaceAfter=30,
            alignment=TA_CENTER
        ))
        
        self.styles.add(ParagraphStyle(
            name='SectionHeader',
            parent=self.styles['Heading2'],
            fontSize=16,
            textColor=colors.HexColor('#283593'),
            spaceAfter=12,
            spaceBefore=12
        ))
        
        self.styles.add(ParagraphStyle(
            name='StepText',
            parent=self.styles['Normal'],
            fontSize=11,
            spaceAfter=8,
            leftIndent=20
        ))
        
        self.styles.add(ParagraphStyle(
            name='ExplanationText',
            parent=self.styles['Normal'],
            fontSize=10,
            spaceAfter=6,
            leftIndent=30,
            textColor=colors.HexColor('#424242')
        ))
    
    def generate_pdf(
        self,
        output_path: str,
        input_image_path: str,
        annotated_image_path: str,
        task: str,
        target_component: Dict[str, Any],
        sop_data: Dict[str, Any],
        explanations: List[Dict[str, Any]],
        qa_result: Dict[str, Any],
        all_components: List[Dict[str, Any]] = None
    ) -> str:
        """Generate complete SOP PDF report"""
        doc = SimpleDocTemplate(output_path, pagesize=letter)
        story = []
        
        # Title Page
        story.extend(self._create_title_page(task, target_component))
        story.append(PageBreak())
        
        # Table of Contents
        story.extend(self._create_table_of_contents())
        story.append(PageBreak())
        
        # Input Image Section
        story.extend(self._create_image_section("Input Motherboard Image", input_image_path))
        story.append(Spacer(1, 0.3*inch))
        
        # Annotated Image Section
        story.extend(self._create_image_section("Annotated Image (Components Detected)", annotated_image_path))
        story.append(PageBreak())
        
        # All Detected Components Section
        if all_components:
            story.extend(self._create_all_components_section(all_components))
            story.append(Spacer(1, 0.2*inch))
        
        # Detected Component Section
        story.extend(self._create_component_section(target_component))
        story.append(Spacer(1, 0.2*inch))
        
        # SOP Steps Section
        story.extend(self._create_sop_section(sop_data))
        story.append(Spacer(1, 0.2*inch))
        
        # Detailed Explanations Section
        story.extend(self._create_explanations_section(explanations))
        story.append(Spacer(1, 0.2*inch))
        
        # Safety Notes Section
        story.extend(self._create_safety_section(target_component, qa_result))
        
        # Build PDF
        doc.build(story)
        return output_path
    
    def _create_title_page(self, task: str, target_component: Dict[str, Any]) -> List:
        """Create title page"""
        elements = []
        
        title = Paragraph(
            f"AI-Generated SOP<br/>{task}",
            self.styles['CustomTitle']
        )
        elements.append(Spacer(1, 2*inch))
        elements.append(title)
        elements.append(Spacer(1, 0.5*inch))
        
        subtitle = Paragraph(
            f"Component: {target_component.get('name', 'Unknown')}<br/>"
            f"Connector Type: {target_component.get('connector_type', 'Unknown')}<br/>"
            f"Risk Level: {target_component.get('risk_level', 'Medium')}",
            self.styles['Normal']
        )
        elements.append(subtitle)
        elements.append(Spacer(1, 1*inch))
        
        footer = Paragraph(
            "Generated by Multi-Agent AI System<br/>"
            "Manufacturing SOP Automation Platform",
            ParagraphStyle(
                name='Footer',
                parent=self.styles['Normal'],
                fontSize=9,
                textColor=colors.grey,
                alignment=TA_CENTER
            )
        )
        elements.append(footer)
        
        return elements
    
    def _create_table_of_contents(self) -> List:
        """Create table of contents"""
        elements = []
        elements.append(Paragraph("Table of Contents", self.styles['SectionHeader']))
        elements.append(Spacer(1, 0.2*inch))
        
        toc_items = [
            "Input Motherboard Image",
            "Annotated Image (Components Detected)",
            "All Detected Connectors/Slots",
            "Target Component Information",
            "SOP Steps",
            "Detailed Explanations",
            "Safety Notes and QA Validation"
        ]
        
        for item in toc_items:
            elements.append(Paragraph(f"• {item}", self.styles['Normal']))
            elements.append(Spacer(1, 0.1*inch))
        
        return elements
    
    def _create_image_section(self, title: str, image_path: str) -> List:
        """Create image section"""
        elements = []
        elements.append(Paragraph(title, self.styles['SectionHeader']))
        
        if os.path.exists(image_path):
            # Resize image to fit page
            img = PILImage.open(image_path)
            img_width, img_height = img.size
            max_width = 6*inch
            max_height = 4*inch
            
            # Calculate scaling
            scale_w = max_width / img_width
            scale_h = max_height / img_height
            scale = min(scale_w, scale_h)
            
            img_width_scaled = img_width * scale
            img_height_scaled = img_height * scale
            
            reportlab_img = Image(image_path, width=img_width_scaled, height=img_height_scaled)
            elements.append(reportlab_img)
        else:
            elements.append(Paragraph("Image not available", self.styles['Normal']))
        
        return elements
    
    def _create_all_components_section(self, all_components: List[Dict[str, Any]]) -> List:
        """Create section showing all detected connectors"""
        elements = []
        elements.append(Paragraph("All Detected Connectors/Slots on Motherboard", self.styles['SectionHeader']))
        
        # Create table data
        table_data = [["Connector Name", "Type", "Device Slot", "Risk Level", "Voltage"]]
        
        device_slot_mapping = {
            "Keyboard Connector": "Keyboard Slot",
            "RAM Slot": "Memory Module Slot (SO-DIMM)",
            "Fan Connector": "CPU/System Fan Slot",
            "Battery Connector": "Battery Power Slot",
            "Display Connector": "LCD/Display Panel Slot",
            "USB Connector": "USB Port Slot",
            "Power Connector": "DC Power Input Slot"
        }
        
        for comp in all_components:
            comp_name = comp.get('name', 'Unknown')
            device_slot = device_slot_mapping.get(comp_name, f"{comp_name} Slot")
            table_data.append([
                comp_name,
                comp.get('connector_type', 'Unknown'),
                device_slot,
                comp.get('risk_level', 'Medium'),
                comp.get('voltage', 'Unknown')
            ])
        
        table = Table(table_data, colWidths=[1.5*inch, 1.2*inch, 1.8*inch, 1*inch, 1*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1a237e')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('GRID', (0, 0), (-1, -1), 1, colors.grey),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f5f5f5')])
        ]))
        elements.append(table)
        
        elements.append(Spacer(1, 0.1*inch))
        elements.append(Paragraph(
            f"<b>Total Connectors Detected:</b> {len(all_components)}",
            self.styles['Normal']
        ))
        
        return elements
    
    def _create_component_section(self, target_component: Dict[str, Any]) -> List:
        """Create component information section"""
        elements = []
        elements.append(Paragraph("Target Component Information (For SOP)", self.styles['SectionHeader']))
        
        data = [
            ["Component Name:", target_component.get('name', 'Unknown')],
            ["Connector Type:", target_component.get('connector_type', 'Unknown')],
            ["Risk Level:", target_component.get('risk_level', 'Medium')],
            ["Voltage:", target_component.get('voltage', 'Unknown')],
            ["Pin Count:", target_component.get('pin_count', 'Unknown')],
            ["Orientation:", target_component.get('orientation', 'Unknown')]
        ]
        
        table = Table(data, colWidths=[2*inch, 4*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#e3f2fd')),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('GRID', (0, 0), (-1, -1), 1, colors.grey)
        ]))
        elements.append(table)
        
        return elements
    
    def _create_sop_section(self, sop_data: Dict[str, Any]) -> List:
        """Create SOP steps section"""
        elements = []
        elements.append(Paragraph("Standard Operating Procedure Steps", self.styles['SectionHeader']))
        
        sop_steps = sop_data.get('sop_steps', [])
        for idx, step in enumerate(sop_steps, 1):
            step_text = f"<b>Step {idx}:</b> {step}"
            elements.append(Paragraph(step_text, self.styles['StepText']))
            elements.append(Spacer(1, 0.1*inch))
        
        return elements
    
    def _create_explanations_section(self, explanations: List[Dict[str, Any]]) -> List:
        """Create detailed explanations section"""
        elements = []
        elements.append(Paragraph("Detailed Step-by-Step Explanations", self.styles['SectionHeader']))
        
        for exp in explanations:
            step_num = exp.get('step_number', 0)
            step_text = exp.get('step_text', '')
            explanation = exp.get('explanation', '')
            why = exp.get('why_important', '')
            mistakes = exp.get('common_mistakes', '')
            
            elements.append(Paragraph(
                f"<b>Step {step_num}: {step_text}</b>",
                self.styles['StepText']
            ))
            elements.append(Paragraph(
                f"<b>Explanation:</b> {explanation}",
                self.styles['ExplanationText']
            ))
            elements.append(Paragraph(
                f"<b>Why Important:</b> {why}",
                self.styles['ExplanationText']
            ))
            if mistakes:
                elements.append(Paragraph(
                    f"<b>Common Mistakes:</b> {mistakes}",
                    self.styles['ExplanationText']
                ))
            elements.append(Spacer(1, 0.15*inch))
        
        return elements
    
    def _create_safety_section(self, target_component: Dict[str, Any], qa_result: Dict[str, Any]) -> List:
        """Create safety notes section"""
        elements = []
        elements.append(Paragraph("Safety Notes and QA Validation", self.styles['SectionHeader']))
        
        # Safety notes from component
        safety_notes = target_component.get('safety_notes', [])
        if safety_notes:
            elements.append(Paragraph("<b>Component Safety Notes:</b>", self.styles['Normal']))
            for note in safety_notes:
                elements.append(Paragraph(f"• {note}", self.styles['Normal']))
            elements.append(Spacer(1, 0.1*inch))
        
        # QA Results
        qa_status = qa_result.get('status', 'Unknown')
        qa_warnings = qa_result.get('warnings', [])
        qa_recommendations = qa_result.get('recommendations', [])
        safety_score = qa_result.get('safety_score', 0)
        
        elements.append(Paragraph(f"<b>QA Status:</b> {qa_status}", self.styles['Normal']))
        elements.append(Paragraph(f"<b>Safety Score:</b> {safety_score:.1f}/100", self.styles['Normal']))
        elements.append(Spacer(1, 0.1*inch))
        
        if qa_warnings:
            elements.append(Paragraph("<b>Warnings:</b>", self.styles['Normal']))
            for warning in qa_warnings:
                elements.append(Paragraph(f"⚠ {warning}", self.styles['Normal']))
            elements.append(Spacer(1, 0.1*inch))
        
        if qa_recommendations:
            elements.append(Paragraph("<b>Recommendations:</b>", self.styles['Normal']))
            for rec in qa_recommendations:
                elements.append(Paragraph(f"• {rec}", self.styles['Normal']))
        
        return elements

